### ISSUE TITLE
Python Porting

### ISSUE THREAD

**Issue by Resousse** [guillaumeblaquiere/cloudrun-sigterm-selfcall#1]
Hello @guillaumeblaquiere , 

I've read your very interesting article on Medium about this matter.
And I didn't find any implementation of this in Python, so I wrote a port of your third solution : https://github.com/Resousse/cloudrun-stay-awake

Let me know if you heard about other Python implementation, or if my implementation seems correct to you.

Regards,
Bonne année!

**Comment by guillaumeblaquiere** [comment]
Hey @Resousse, it's a great implementation that should work (I reviewed the code without running it, but it seems great!)

However, you use something in your code that lead me to dislike python. Have a look to your [line 26](https://github.com/Resousse/cloudrun-stay-awake/blob/ae3a4358611df2a3e3760867833a90af1e1c01a5/main.py#L26) and [line 35](https://github.com/Resousse/cloudrun-stay-awake/blob/ae3a4358611df2a3e3760867833a90af1e1c01a5/main.py#L35): You use the same variable name, but 1 time it's JSON structure, the other it's raw text.

That led me to confusion and I tested the metadata calls to be sure that you haven't issue on that. And no, your code is correct, but the multi-type variable always disturb me!!
